"""Calibration scan tests.

The property that matters: a band read off the curve must produce exactly the
emission count the curve promised, because the curve is generated by running the
detector rather than by modelling it.
"""
from __future__ import annotations

import json

import pytest

from nar001 import calibration as cal
from nar001.detector import REGISTRY, ChangeDetector, SignalSpec, required_parameters

from fixtures import tick
from test_detector import CATALOGUE, feed, new, ramp

SPEC = next(s for s in REGISTRY if s.signal == "LOAD.p_demand_mw")


def jitter_with_steps(n_steps=6, per_step=40, jitter=0.02, step=2.0, base=10.0):
    """A signal with small jitter and large discrete steps -- the shape the scan
    has to separate."""
    vals, v = [], base
    for s in range(n_steps):
        for k in range(per_step):
            vals.append(v + (jitter if k % 2 else -jitter))
        v += step
    return vals


def test_scan_separates_jitter_from_steps():
    payloads = ramp(jitter_with_steps())
    row = cal.scan_signal(payloads, SPEC)
    # jitter dominates the delta distribution; the steps sit in the tail
    assert row["nonzero_deltas"]["p50"] == pytest.approx(0.04, abs=1e-9)
    assert row["nonzero_deltas"]["max"] == pytest.approx(2.0 - 0.04, abs=1e-9)
    assert row["noise_floor_estimate"] == pytest.approx(0.04, abs=1e-9)


def test_curve_promise_matches_detector_behaviour():
    """A band read off the curve must emit exactly what the curve said."""
    payloads = ramp(jitter_with_steps())
    row = cal.scan_signal(payloads, SPEC)
    for point in row["curve"]:
        det = ChangeDetector({**CATALOGUE, "deadband_power_mw": point["band"]})
        actual = len([r for r in feed(det, payloads, "LOAD.p_demand_mw")])
        assert actual == point["emissions"], point


def test_emissions_are_monotonic_non_increasing_in_band():
    payloads = ramp(jitter_with_steps())
    counts = [cal.emissions_at(payloads, SPEC, b)
              for b in (0.01, 0.05, 0.5, 1.0, 3.0, 30.0)]
    assert counts == sorted(counts, reverse=True)
    assert counts[-1] == 0          # a band above the total range emits nothing


def test_a_band_above_the_largest_step_does_not_silence_a_ramp():
    """Hysteresis is against the last reported value, so cumulative drift keeps
    firing even when every individual step is inside the band. A band is silenced
    by the signal's total range, not by its step size -- which is the property
    that stops a slow ramp being lost, and is easy to mis-predict when reading a
    calibration curve."""
    payloads = ramp(jitter_with_steps(n_steps=6, step=2.0))   # range ~10 MW
    assert cal.emissions_at(payloads, SPEC, 3.0) == 2         # > step, still fires
    assert cal.emissions_at(payloads, SPEC, 30.0) == 0        # > range, silent


def test_a_band_above_the_noise_recovers_the_step_count():
    payloads = ramp(jitter_with_steps(n_steps=6, step=2.0))
    # 6 steps, the first establishing the baseline -> 5 transitions observed
    assert cal.emissions_at(payloads, SPEC, 0.5) == 5


def test_flat_signal_yields_no_candidates():
    row = cal.scan_signal(ramp([10.0] * 50), SPEC)
    assert row["curve"] == []
    assert row["still_fraction"] == pytest.approx(1.0)
    assert row["noise_floor_estimate"] is None


def test_single_value_signal_is_reported_not_crashed():
    row = cal.scan_signal(ramp([10.0]), SPEC)
    assert "note" in row and "nothing to calibrate" in row["note"]


def test_absent_signal_is_reported_not_crashed():
    payloads = ramp([10.0, 11.0, 12.0])
    for p in payloads:
        p.pop("frequency_hz", None)
    spec = next(s for s in REGISTRY if s.signal == "GEN.frequency_hz")
    row = cal.scan_signal(payloads, spec)
    assert row["values"]["n"] == 0
    assert "nothing to calibrate" in row["note"]


def test_edge_signals_report_no_band_to_calibrate():
    spec = next(s for s in REGISTRY if s.signal == "GEN.commitment_action")
    row = cal.scan_signal(ramp([10.0, 11.0]), spec)
    assert row["note"] == "not deadbanded; no band to calibrate"
    assert "curve" not in row


def test_scan_groups_signals_by_shared_band_key():
    """One key serves many signals, so a band chosen for one is imposed on all.
    The report has to surface that trade-off."""
    vals = jitter_with_steps()
    payloads = []
    for i, v in enumerate(vals):
        payloads.append(tick(sim_time_seconds=float(i * 5),
                             p_demand_mw=v, p_total_mw=v,
                             turbine_output_mw=v * 0.6))
    result = cal.scan(payloads)
    shared = {r["signal"] for r in result["by_band_key"]["deadband_power_mw"]}
    assert {"LOAD.p_demand_mw", "GEN.turbine_output_mw"} <= shared


def test_scan_proposes_no_values():
    """The scan reports curves. Choosing is a DR, not a computation."""
    text = cal.format_scan(cal.scan(ramp(jitter_with_steps())))
    assert "Nothing here proposes a value" in text
    for banned in ("recommended", "suggested band", "use "):
        assert banned not in text.lower()


def test_scan_output_is_deterministic():
    payloads = ramp(jitter_with_steps())
    a = json.dumps(cal.scan(payloads), sort_keys=True, default=str)
    b = json.dumps(cal.scan(payloads), sort_keys=True, default=str)
    assert a == b


def test_disabled_band_silences_a_signal_entirely():
    payloads = ramp([10.0 + i for i in range(20)])
    assert cal.emissions_at(payloads, SPEC, cal.DISABLED) == 0


def test_sweep_uses_the_real_detector_not_a_delta_count():
    """A slow ramp crossing one band in ten tiny steps emits once under
    hysteresis, but zero times under a naive |delta| >= band count. The scan must
    report one."""
    band = 1.0
    payloads = ramp([10.0 + i * 0.1 for i in range(11)])
    naive = sum(1 for d in cal._deltas([10.0 + i * 0.1 for i in range(11)])
                if d >= band)
    assert naive == 0
    assert cal.emissions_at(payloads, SPEC, band) == 1


def test_cli_refuses_to_run_without_a_catalogue(tmp_path, capsys):
    from nar001 import feed as feedcli
    p = tmp_path / "run-a.jsonl"
    with p.open("w") as fh:
        for i, v in enumerate([10.0, 11.0]):
            fh.write(json.dumps({"seq": i, "received_wall_utc": "x",
                                 "payload": tick(sim_time_seconds=float(i * 5),
                                                 p_demand_mw=v, p_total_mw=v)}) + "\n")
    rc = feedcli.main([str(tmp_path)])
    out = capsys.readouterr().out
    assert rc == 2
    assert "calibration scan" in out
    for k in required_parameters():
        assert k in out


def test_cli_calibrate_runs_without_a_catalogue(tmp_path, capsys):
    from nar001 import feed as feedcli
    p = tmp_path / "run-b.jsonl"
    with p.open("w") as fh:
        for i, v in enumerate(jitter_with_steps(n_steps=3, per_step=10)):
            fh.write(json.dumps({"seq": i, "received_wall_utc": "x",
                                 "payload": tick(sim_time_seconds=float(i * 5),
                                                 p_demand_mw=v, p_total_mw=v)}) + "\n")
    assert feedcli.main([str(tmp_path), "--calibrate"]) == 0
    assert "signals with a band to calibrate" in capsys.readouterr().out


def test_cli_reports_missing_catalogue_keys(tmp_path, capsys):
    from nar001 import feed as feedcli
    p = tmp_path / "run-c.jsonl"
    with p.open("w") as fh:
        fh.write(json.dumps({"seq": 0, "received_wall_utc": "x",
                             "payload": tick()}) + "\n")
    cat = tmp_path / "cat.json"
    cat.write_text(json.dumps({"deadband_power_mw": 0.5}))
    rc = feedcli.main([str(tmp_path), "--catalogue", str(cat)])
    assert rc == 2
    assert "missing required parameters" in capsys.readouterr().out


# ------------------------------------- regressions found by running the scan
def test_curve_has_more_than_one_point_on_uniform_steps():
    """Every percentile collapses to the same value when steps are uniform, so a
    percentile-only grid degenerates to a single point that cannot be read."""
    row = cal.scan_signal(ramp(jitter_with_steps(n_steps=4, per_step=20,
                                                 jitter=0.0)), SPEC)
    bands = [c["band"] for c in row["curve"]]
    assert len(bands) >= 5
    assert bands == sorted(bands)
    assert bands[0] < bands[-1]


def test_low_rate_signal_reports_raw_counts_not_a_rounded_rate():
    """Two changes in 800 ticks is 0.25 per 100 and rounds away to zero. The
    curve must carry the count."""
    vals = [10.0] * 400 + [20.0] * 400
    row = cal.scan_signal(ramp(vals), SPEC)
    small = row["curve"][0]
    assert small["emissions"] == 1
    assert small["per_100_ticks"] < 0.5      # would display as 0 if rounded


def test_dithering_signal_shows_a_cliff():
    """A signal with pure dither is silenced entirely by any band above its
    peak-to-peak, and the cliff is where the band should be read."""
    vals = [60.0 + (0.02 if i % 2 else -0.02) for i in range(200)]
    spec = next(s for s in REGISTRY if s.signal == "GEN.frequency_hz")
    payloads = [tick(sim_time_seconds=float(i * 5), frequency_hz=v)
                for i, v in enumerate(vals)]
    row = cal.scan_signal(payloads, spec)
    # Read the cliff from the scan, not from a literal: the observed floor here
    # is 0.040000000000006, so comparing bands against a hand-written 0.04 puts
    # the floor itself on the wrong side of the split.
    floor = row["noise_floor_estimate"]
    below = [c for c in row["curve"] if c["band"] <= floor]
    above = [c for c in row["curve"] if c["band"] > floor]
    assert below and above
    assert all(c["emissions"] > 0 for c in below)
    assert all(c["emissions"] == 0 for c in above)
    assert row["travel_ratio"] == pytest.approx(0.0, abs=0.02)   # retraces


def test_drifting_signal_has_no_cliff_and_is_labelled():
    """A monotonic drift never repeats a value, so no band silences it until the
    band exceeds the total range. The band is then a reporting policy."""
    vals = [0.95 - i * 0.0004 for i in range(400)]
    spec = next(s for s in REGISTRY if s.signal == "GEN.bess_soc_fraction")
    payloads = [tick(sim_time_seconds=float(i * 5), bess_soc_fraction=v)
                for i, v in enumerate(vals)]
    row = cal.scan_signal(payloads, spec)
    assert row["travel_ratio"] == pytest.approx(1.0, abs=1e-9)    # never retraces
    assert row["still_fraction"] == 0.0
    counts = [c["emissions"] for c in row["curve"]]
    assert counts == sorted(counts, reverse=True)
    assert counts[0] > counts[-1] > 0        # smooth decline, no cliff to zero


def test_rate_signal_silent_at_every_band_is_flagged():
    row = cal.scan_signal(ramp(jitter_with_steps()),
                          next(s for s in REGISTRY
                               if s.signal == "LOAD.p_demand_rate"))
    assert all(c["emissions"] == 0 for c in row["curve"])
    assert "structurally blind" in row["note"]


def test_travel_ratio_separates_dither_from_drift():
    """still_fraction cannot tell them apart -- an alternating signal never
    repeats a value either, so both read as 'always moving'. Net displacement
    over path length does separate them, and they need different bands."""
    dither = [60.0 + (0.02 if i % 2 else -0.02) for i in range(100)]
    drift = [60.0 + i * 0.02 for i in range(100)]
    spec = next(s for s in REGISTRY if s.signal == "GEN.frequency_hz")
    rows = {}
    for name, vals in (("dither", dither), ("drift", drift)):
        payloads = [tick(sim_time_seconds=float(i * 5), frequency_hz=v)
                    for i, v in enumerate(vals)]
        rows[name] = cal.scan_signal(payloads, spec)
    assert rows["dither"]["still_fraction"] == rows["drift"]["still_fraction"] == 0.0
    assert rows["dither"]["travel_ratio"] < 0.05
    assert rows["drift"]["travel_ratio"] == pytest.approx(1.0, abs=1e-9)
