// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pms-redesign/OperationalReadiness.tsx": () => import("../components/mockups/pms-redesign/OperationalReadiness.tsx"),
  "./components/mockups/demo-sharing-flow/PrivateSharedDemo.tsx": () => import("../components/mockups/demo-sharing-flow/PrivateSharedDemo.tsx")
};
